# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

# Check the goreleaser documentation at https://goreleaser.com

version: 1

before:
  hooks:
    - go mod tidy
    - go vet
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
      - "GOFLAGS=-mod=readonly -trimpath" # trimpath helps with producing verifiable binaries
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      # the following line will inject the current version in the binary during the build process.
      # .Version is a template variable that will be set during the GoReleaser run
      # The "-X" go flag injects a string into the two global variables Version
      # See also: https://pkg.go.dev/cmd/link
      - -s
      - -w
      - -X github.com/geowa4/servicelogger/pkg/version.Version={{.Version}}
      - "-extldflags=-zrelro" # binary hardening: For further explanation look here: https://www.redhat.com/en/blog/hardening-elf-binaries-using-relocation-read-only-relro
      - "-extldflags=-znow"

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
